# Generated by Django 3.2.6 on 2021-08-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
            ],
        ),
    ]
